### ISSUE TITLE
验证信息存放位置？

### ISSUE THREAD

**Issue by racooncry** [pipijoe/auth#1]
是把spring security的验证信息都放在map里面吗？
我感觉jwt本身是所有数据都根据token解析出来的啊，因为不放内存所以才用

**Comment by pipijoe** [comment]
不敏感的信息都可以放在token里，服务器就可以不存储用户状态了。
用户登陆之后的信息，包括权限是存在security context中，是为了之后访问Api鉴权使用。

**Comment by pipijoe** [comment]
> 是把spring security的验证信息都放在map里面吗？
> 我感觉jwt本身是所有数据都根据token解析出来的啊，因为不放内存所以才用

不敏感的信息都可以放在token里，服务器就可以不存储用户状态了。
用户登陆之后的信息，包括权限是存在security context中，是为了之后访问Api鉴权使用。
