### ISSUE TITLE
jwt里面的getUsernameFromToken方法

### ISSUE THREAD

**Issue by Mrcici** [pipijoe/auth#2]
数据库里面的用户名是不是只能用username，你这里用的是name,你有在项目里试过登录吗？通过内置的方法获取UserDetails的时候，username是空的，然后一直通过token访问其他都一直说401

**Comment by pipijoe** [comment]
数据库字段名字不一定要username.
token在生成的过程中是将一些用户信息编码进去的，也就可以反编码获取。UserDetail是不能直接拿到的，你将哪些用户信息编码进token了，才能拿到相应的数据，其他数据拿不到。

**Comment by Mrcici** [comment]
但是我在调试的时候，用你的源代码，通过token访问api/v1/user的时候，不能够访问呀，401

**Comment by Mrcici** [comment]
然后把user的表里面的name，改成username就可以了

**Comment by Mrcici** [comment]
然后现在遇到一个问题，我是想整合到springcloud里面，但是我在项目加入feign以后，连login这些默认可以访问的url也被拦截器给拦截掉了，这两天都在想这个问题

**Comment by pipijoe** [comment]
feign不清楚，可以打个断点看一下拦截器拦截的真正请求是什么
