### ISSUE TITLE
clone项目下来运行，只要注册没问题的，其它接口都出错了

### ISSUE THREAD

**Issue by aleaxmaster** [pipijoe/auth#3]

**Comment by pipijoe** [comment]
能提供一下出错信息吗？

**Comment by aleaxmaster** [comment]
运行起来先是注册了账号密码均为root的用户成功，接着登录报错，swagger返回500
`{
  "timestamp": "2019-03-16T14:59:15.843+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "No message available",
  "path": "/api/v1/login"
}`
控制台报空指针错误，具体是`(UserDetail.java:52)，(AuthServiceImpl.java:109)，(AuthServiceImpl.java:69)，(AuthController.java:46)(JwtAuthenticationTokenFilter.java:58)`这几个类的代码处有问题，看了下好像是User实体类没有设置getset方法。等我添加上去试试。因为登录不了，其它接口没跑，还没怎么看懂你代码

**Comment by aleaxmaster** [comment]
对了，还有一个细节。User实体类你设置了最短六位+，但在注册时没有做这个判断导致后面登录提示密码过短？

**Comment by pipijoe** [comment]
getset方法是通过注解@Data实现的，你的编辑器需要安装一个lombok插件
