### ISSUE TITLE
真的是垃圾，这项目新手能跑起来我拜他为师

### ISSUE THREAD

**Issue by javaygq** [pipijoe/auth#4]
各种坑，我不知道博主是不是故意的

**Comment by javaygq** [comment]
![image](https://user-images.githubusercontent.com/34884079/54795912-f61efd00-4c88-11e9-9c91-13756a0bc925.png)
这个地方不加注解能跑起来我剁手，新手绝对找不出答案来

**Comment by javaygq** [comment]
![image](https://user-images.githubusercontent.com/34884079/54796035-89f0c900-4c89-11e9-96f3-cb32f481ea48.png)
觉得博主没有仔细运行该项目，瞎搞

**Comment by pipijoe** [comment]
spring官方已经不再推荐在属性上加@AutoWired注解了，注入通过构造函数进行。
另外，这个项目也不是给新手用的，新手应该在这个阶段接触不到权限控制这些功能。

**Comment by javaygq** [comment]
不加能跑起来？？？？

**Comment by pipijoe** [comment]
authMapper.insert(userDetail)，会将自增id重新装配进userDetail。你可以去看authMapper的sql

**Comment by pipijoe** [comment]
另外，怨气太重，是不是加班加多了？

**Comment by javaygq** [comment]
我看了SQL，你写的有问题，我也知道你加了返回自增，你自己试试就知道了

**Comment by pipijoe** [comment]
欢迎指出问题

**Comment by javaygq** [comment]
![image](https://user-images.githubusercontent.com/34884079/54796358-e9030d80-4c8a-11e9-8968-f0dd6de8dabb.png)
这里你确定是这样？？？

**Comment by javaygq** [comment]
![image](https://user-images.githubusercontent.com/34884079/54796394-0a63f980-4c8b-11e9-9f5e-c72711d30fbe.png)
你确定表里不是这样的？？？

**Comment by pipijoe** [comment]
好的，我会查看一下，谢谢

**Comment by pipijoe** [comment]
谢谢指出问题，已修改。
