### ISSUE TITLE
登录的接口返回给前端的数据的token前面没有带Bearer ，每次调接口还得自己加上去

### ISSUE THREAD

**Issue by javaygq** [pipijoe/auth#5]

**Comment by javaygq** [comment]
这个要改进一下
![image](https://user-images.githubusercontent.com/34884079/54799637-06d76f00-4c99-11e9-86b7-be9fc974a967.png)
加了之后接口就会返回Bearer ，
![image](https://user-images.githubusercontent.com/34884079/54799685-3b4b2b00-4c99-11e9-8dee-27d57e27a99c.png)

**Comment by pipijoe** [comment]
这个返回结果的问题跟前端商量好规则就好了
