### ISSUE TITLE
大佬 为什么我启动项目在swwagger中登入报401

### ISSUE THREAD

**Issue by lichun-rgb** [pipijoe/auth#7]

**Comment by lichun-rgb** [comment]
<img width="722" alt="微信截图_20191112085457" src="https://user-images.githubusercontent.com/57647211/68632624-22de9800-052a-11ea-9e9d-e479cf44cb21.png">

**Comment by pipijoe** [comment]
查看一下你的WebSecurity配置类

**Comment by lichun-rgb** [comment]
我直接拉你的代码启动的

**Comment by pipijoe** [comment]
登陆之前需要自己先注册账号，再登陆。有问题，希望能提供更详细的问题说明

**Comment by lichun-rgb** [comment]
我看到你有注册的功能 但是没有注册和登入的页面 是要自己实现么？

**Comment by pipijoe** [comment]
是的
